<?php

/**
 * @file
 * Contains bhcc_webform.triage.module hook implemtations.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_webform_submission_form_alter().
 */
function bhcc_webform_triage_webform_submission_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $webform = $form_state->getFormObject()->getEntity()->getWebform();

  // If the webform contains the thrid party setting 'triage_enable',
  // enable triage form behaviours.
  $triage_enable = $webform->getThirdPartySetting('bhcc_webform_triage', 'triage_enable');
  if ($triage_enable && !empty($form['#attached']['library'])) {

    // Remove the form unsaved library for triage forms.
    $form['#attached']['library'] = array_filter($form['#attached']['library'], function ($item) {
      return $item == 'webform/webform.form.unsaved' ? FALSE : TRUE;
    });
  }
}

/**
 * Implements hook_form_webform_settings_form_alter().
 */
function bhcc_webform_triage_form_webform_settings_form_alter(array &$form, FormStateInterface $form_state) {

  // Adds a setting for enabling triage mode.
  $webform = $form_state->getFormObject()->getEntity();
  $triage_enable = $webform->getThirdPartySetting('bhcc_webform_triage', 'triage_enable');
  $form['bhcc_triage'] = [
    '#type' => 'details',
    '#title' => t('Triage behaviour'),
    '#weight' => 1,
  ];
  $form['bhcc_triage']['triage'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable triage form behaviour'),
    '#description' => t('Triage forms will disable the unsaved message.'),
    '#default_value' => $triage_enable,
  ];
  $form['actions']['submit']['#submit'][] = '_bhcc_webform_triage_webform_settings_form_submit';
}

/**
 * Webform triage settings form submit handler.
 *
 * Saves the triage mode to third party settings of a webform.
 *
 * @param array $form
 *   Form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Form state object.
 */
function _bhcc_webform_triage_webform_settings_form_submit(array $form, FormStateInterface $form_state) {
  $webform = $form_state->getFormObject()->getEntity();
  $triage_enable = $form_state->getValue('triage');
  if ($triage_enable) {
    $webform->setThirdPartySetting('bhcc_webform_triage', 'triage_enable', $triage_enable);
  }

  // If triage is set to false, best to remove it.
  // This would allow the module to be uninstalled once no forms require it.
  else {
    $webform->unsetThirdPartySetting('bhcc_webform_triage', 'triage_enable');
  }
  $webform->save();
}
